### ISSUE TITLE
The tx go to emergency mode

### ISSUE THREAD

**Issue by robustini** [iNavFlight/OpenTX-Telemetry-Widget#42] opened 2022-04-30 07:44 UTC
I have never been able to get this version to work on my Horus X10S Express, with the latest official OpenTX firmware.
As soon as I select the widget the tx goes into emergency mode.
While this version works, and I can't figure out if yours is a newer version than that.: https://github.com/teckel12/LuaTelemetry/releases/tag/v1.7.5

**Comment by dchuryn** [comment] 2022-05-01 03:09
Same issue on both a TX16s and X10s Express running OpenTX 2.3.15.   Down grading to 2.3.13, which I had been running previously resolved the issue.

**Comment by stronnag** [comment] 2022-05-01 06:48
Duplicate of #40 and https://github.com/opentx/opentx/issues/8909

**Closed by stronnag** 2022-05-01 06:48 UTC
